# Generated by Django 4.2.1 on 2023-06-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категорий'),
            preserve_default=False,
        ),
    ]
